import { test } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { checkSpelling } from './spell-check.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BASE_URL = process.env.QA_BASE_URL || 'http://localhost:8080';
const EXPECTED_DOMAIN = process.env.QA_EXPECTED_DOMAIN || '';

type Issue = {
  url: string;
  type: string;
  message: string;
};

const issues: Issue[] = [];

// URLs are loaded synchronously from urls.json, which is pre-generated by
// tools/qa/prefetch-urls.ts before Playwright runs (see `qa` npm script).
// This approach is required because Playwright generates test cases at module
// evaluation time — a beforeAll callback cannot populate the list in time.
const urlsJsonPath = path.join(__dirname, 'urls.json');
if (!fs.existsSync(urlsJsonPath)) {
  throw new Error(
    '[QA] urls.json not found. Run `pnpm qa` (not `playwright test` directly) ' +
      'so the prefetch step runs first, or execute `tsx tools/qa/prefetch-urls.ts` manually.',
  );
}
const urls: string[] = JSON.parse(fs.readFileSync(urlsJsonPath, 'utf-8'));

function addIssue(url: string, type: string, message: string) {
  issues.push({ url, type, message });
}

function normalizePhone(value: string): string {
  return value.replace(/[^\d]/g, '');
}

/**
 * Captures a screenshot tied to a specific issue.
 *
 * - If `element` is provided the screenshot is clipped to that element.
 * - Otherwise a viewport-only screenshot is taken.
 * - Errors (detached element, closed page, etc.) are silently swallowed so a
 *   screenshot failure never blocks the rest of the scan.
 *
 * Files are named: `{screenshotDir}/{safeName}--{label}.png`
 */
async function captureIssueScreenshot(
  screenshotDir: string,
  safeName: string,
  label: string,
  page: any,
  element?: any,
) {
  fs.mkdirSync(screenshotDir, { recursive: true });
  // Sanitise the label so it is safe as a filename fragment
  const safeLabel = label.replace(/[^a-z0-9_\-]/gi, '-').toLowerCase();
  const filePath = path.join(screenshotDir, `${safeName}--${safeLabel}.png`);
  try {
    if (element) {
      await element.screenshot({ path: filePath });
    } else {
      await page.screenshot({ path: filePath, fullPage: false });
    }
  } catch {
    // screenshot failed — skip silently
  }
}

async function waitForAppReady(page: any) {
  await page.waitForLoadState('domcontentloaded');

  await page.waitForFunction(
    () => {
      const root = document.querySelector('#root');
      if (!root) return false;

      const text = (root.textContent || '').trim();
      const hasMeaningfulText = text.length > 30;

      const hasMain = !!document.querySelector('main');
      const hasHeader = !!document.querySelector('header');
      const hasH1 = !!document.querySelector('h1');

      return hasMeaningfulText || hasMain || hasHeader || hasH1;
    },
    { timeout: 10000 }
  );

  await page.waitForTimeout(1500);
}

async function getAttr(page: any, selector: string, attr: string): Promise<string> {
  return page.evaluate(
    ({ sel, attribute }: { sel: string; attribute: string }) => {
      const el = document.querySelector(sel);
      return el?.getAttribute(attribute) || '';
    },
    { sel: selector, attribute: attr }
  );
}

async function getPhoneData(page: any) {
  return page.evaluate(() => {
    const telAnchors = Array.from(document.querySelectorAll('a[href^="tel:"]'));

    const telHrefs = telAnchors
      .map((a) => a.getAttribute('href') || '')
      .filter(Boolean);

    const telTexts = telAnchors
      .map((a) => (a.textContent || '').trim())
      .filter(Boolean);

    const bodyText = document.body?.innerText || '';
    const phoneLikeTextMatches =
      bodyText.match(/(?<![\/\d])\+?\d[\d\s().-]{7,}\d/g)?.map((m) => m.trim()) || [];

    return {
      telHrefs,
      telTexts,
      phoneLikeTextMatches,
    };
  });
}

async function checkBrokenInternalLinks(
  page: any,
  urlPath: string,
  screenshotDir: string,
  safeName: string,
) {
  const links = await page.evaluate((baseUrl: string) => {
    const origin = new URL(baseUrl).origin;

    return Array.from(document.querySelectorAll('a[href]'))
      .map((a) => {
        const href = a.getAttribute('href') || '';
        const text = (a.textContent || '').trim();
        return { href, text };
      })
      .filter((link) => {
        if (!link.href) return false;
        if (link.href.startsWith('#')) return false;
        if (link.href.startsWith('mailto:')) return false;
        if (link.href.startsWith('tel:')) return false;
        if (link.href.startsWith('javascript:')) return false;

        try {
          const absolute = new URL(link.href, baseUrl);
          return absolute.origin === origin;
        } catch {
          return false;
        }
      });
  }, BASE_URL);

  const checked = new Set<string>();
  const linksToCheck = links.slice(0, 25);

  for (let index = 0; index < linksToCheck.length; index++) {
    const link = linksToCheck[index];
    try {
      const absolute = new URL(link.href, BASE_URL).toString();

      if (checked.has(absolute)) continue;
      checked.add(absolute);

      const response = await page.request.get(absolute, {
        failOnStatusCode: false,
        timeout: 5000,
      });

      const status = response.status();

      if (status >= 400) {
        addIssue(
          urlPath,
          'links',
          `Broken internal link: ${link.href} returned ${status}`
        );
        let linkElement: any = null;
        try {
          const loc = page.locator(`a[href="${link.href}"]`).first();
          if (await loc.isVisible({ timeout: 1000 })) linkElement = loc;
        } catch { /* fall back to viewport */ }
        await captureIssueScreenshot(screenshotDir, safeName, `links-broken-${index}`, page, linkElement);
      }
    } catch {
      addIssue(urlPath, 'links', `Invalid internal link: ${link.href}`);
      await captureIssueScreenshot(screenshotDir, safeName, `links-invalid-${index}`, page);
    }
  }
}

test.afterAll(async () => {
  const outputDir = path.resolve('tools/qa/reports');
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(
    path.join(outputDir, 'qa-report.json'),
    JSON.stringify(issues, null, 2),
    'utf-8'
  );
});

for (const urlPath of urls) {
  test(`QA scan: ${urlPath}`, async ({ page }, testInfo) => {
    const fullUrl = new URL(urlPath, BASE_URL).toString();

    // Screenshot context — computed once, reused by every captureIssueScreenshot call
    const screenshotDir = path.resolve('tools/qa/screenshots', testInfo.project.name);
    const safeName =
      urlPath === '/' ? 'home' : urlPath.replace(/\//g, '_').replace(/^_/, '');

    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text());
      }
    });

    // --- HTTP status ---
    const response = await page.goto(fullUrl, { waitUntil: 'domcontentloaded' });

    const status = response?.status();
    if (status && status >= 400) {
      addIssue(urlPath, 'http', `Page returned status ${status}`);
      await captureIssueScreenshot(screenshotDir, safeName, `http-${status}`, page);
    }

    // --- Render ---
    try {
      await waitForAppReady(page);
    } catch {
      addIssue(urlPath, 'render', 'App did not appear to finish rendering in time');
      await captureIssueScreenshot(screenshotDir, safeName, 'render-timeout', page);
    }

    // --- SEO: title ---
    const title = await page.title();
    if (!title || !title.trim()) {
      addIssue(urlPath, 'seo', 'Missing page title');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-missing-title', page);
    }

    // --- SEO: meta description ---
    const metaDescription = await getAttr(page, 'meta[name="description"]', 'content');
    if (!metaDescription.trim()) {
      addIssue(urlPath, 'seo', 'Missing meta description');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-missing-description', page);
    }

    // --- SEO: canonical ---
    const canonical = await getAttr(page, 'link[rel="canonical"]', 'href');
    if (!canonical.trim()) {
      addIssue(urlPath, 'seo', 'Missing canonical URL');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-canonical', page);
    } else if (EXPECTED_DOMAIN) {
      try {
        const canonicalUrl = new URL(canonical, BASE_URL);
        if (!canonicalUrl.hostname.includes(EXPECTED_DOMAIN)) {
          addIssue(
            urlPath,
            'seo',
            `Canonical domain mismatch: ${canonicalUrl.hostname} does not match expected domain ${EXPECTED_DOMAIN}`
          );
          await captureIssueScreenshot(screenshotDir, safeName, 'seo-canonical', page);
        }
      } catch {
        addIssue(urlPath, 'seo', `Invalid canonical URL: ${canonical}`);
        await captureIssueScreenshot(screenshotDir, safeName, 'seo-canonical', page);
      }
    }

    // --- SEO: noindex ---
    const robots = await getAttr(page, 'meta[name="robots"]', 'content');
    if (robots.toLowerCase().includes('noindex')) {
      addIssue(urlPath, 'seo', 'Page contains noindex');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-noindex', page);
    }

    // --- SEO: Open Graph ---
    const ogTitle = await getAttr(page, 'meta[property="og:title"]', 'content');
    if (!ogTitle.trim()) {
      addIssue(urlPath, 'seo', 'Missing og:title');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-og', page);
    }

    const ogDescription = await getAttr(page, 'meta[property="og:description"]', 'content');
    if (!ogDescription.trim()) {
      addIssue(urlPath, 'seo', 'Missing og:description');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-og', page);
    }

    const ogImage = await getAttr(page, 'meta[property="og:image"]', 'content');
    if (!ogImage.trim()) {
      addIssue(urlPath, 'seo', 'Missing og:image');
      await captureIssueScreenshot(screenshotDir, safeName, 'seo-og', page);
    }

    // --- Content: H1 ---
    const h1Count = await page.locator('h1').count();
    if (h1Count === 0) {
      addIssue(urlPath, 'content', 'Missing H1');
      await captureIssueScreenshot(screenshotDir, safeName, 'content-missing-h1', page);
    } else if (h1Count > 1) {
      addIssue(urlPath, 'content', `Multiple H1 tags found (${h1Count})`);
      const firstH1 = page.locator('h1').first();
      let h1Element: any = null;
      try {
        if (await firstH1.isVisible({ timeout: 1000 })) h1Element = firstH1;
      } catch { /* fall back to viewport */ }
      await captureIssueScreenshot(screenshotDir, safeName, 'content-multiple-h1', page, h1Element);
    }

    // --- Placeholder: Lorem ipsum ---
    const bodyText = (await page.locator('body').innerText()).toLowerCase();
    if (bodyText.includes('lorem ipsum')) {
      addIssue(urlPath, 'placeholder', 'Found "Lorem Ipsum" text');
      let loremElement: any = null;
      try {
        const loc = page.locator('body').getByText(/lorem ipsum/i).first();
        if (await loc.isVisible({ timeout: 1000 })) loremElement = loc;
      } catch { /* fall back to viewport */ }
      await captureIssueScreenshot(screenshotDir, safeName, 'placeholder-lorem', page, loremElement);
    }

    // --- Accessibility: image alt text ---
    const images = page.locator('img');
    const imageCount = await images.count();

    for (let i = 0; i < imageCount; i++) {
      const img = images.nth(i);
      const alt = await img.getAttribute('alt');
      const src = await img.getAttribute('src');

      if (!alt || !alt.trim()) {
        addIssue(
          urlPath,
          'accessibility',
          `Image missing alt text: ${src ?? 'unknown src'}`
        );
        let imgElement: any = null;
        try {
          if (await img.isVisible({ timeout: 1000 })) imgElement = img;
        } catch { /* fall back to viewport */ }
        await captureIssueScreenshot(screenshotDir, safeName, `accessibility-img-${i}`, page, imgElement);
      }
    }

    // --- Conversion: phone numbers ---
    const phoneData = await getPhoneData(page);

    if (phoneData.telHrefs.length === 0) {
      addIssue(urlPath, 'conversion', 'No tel: links found on page');
      await captureIssueScreenshot(screenshotDir, safeName, 'conversion-no-tel', page);
    }

    const normalizedTelNumbers = phoneData.telHrefs
      .map((href) => href.replace(/^tel:/i, ''))
      .map(normalizePhone)
      .filter(Boolean);

    const uniqueTelNumbers = [...new Set(normalizedTelNumbers)];

    if (uniqueTelNumbers.length > 1) {
      addIssue(
        urlPath,
        'conversion',
        `Multiple different tel: numbers found: ${uniqueTelNumbers.join(', ')}`
      );
      let firstTelElement: any = null;
      try {
        const loc = page.locator('a[href^="tel:"]').first();
        if (await loc.isVisible({ timeout: 1000 })) firstTelElement = loc;
      } catch { /* fall back to viewport */ }
      await captureIssueScreenshot(screenshotDir, safeName, 'conversion-multi-tel', page, firstTelElement);
    }

    const normalizedVisiblePhoneNumbers = phoneData.phoneLikeTextMatches
      .map(normalizePhone)
      .filter((p) => p.length >= 10);

    const uniqueVisiblePhoneNumbers = [...new Set(normalizedVisiblePhoneNumbers)];

    if (
      uniqueTelNumbers.length === 1 &&
      uniqueVisiblePhoneNumbers.length > 0 &&
      !uniqueVisiblePhoneNumbers.includes(uniqueTelNumbers[0])
    ) {
      addIssue(
        urlPath,
        'conversion',
        `Visible phone number text may not match tel: link number. tel: ${uniqueTelNumbers[0]} visible: ${uniqueVisiblePhoneNumbers.join(', ')}`
      );
      let firstTelElement: any = null;
      try {
        const loc = page.locator('a[href^="tel:"]').first();
        if (await loc.isVisible({ timeout: 1000 })) firstTelElement = loc;
      } catch { /* fall back to viewport */ }
      await captureIssueScreenshot(screenshotDir, safeName, 'conversion-tel-mismatch', page, firstTelElement);
    }

    // --- Console errors ---
    if (consoleErrors.length > 0) {
      addIssue(urlPath, 'console', `Console errors found: ${consoleErrors.join(' | ')}`);
      await captureIssueScreenshot(screenshotDir, safeName, 'console-errors', page);
    }

    // --- Spelling ---
    const rawBodyText = await page.locator('body').innerText();
    const spellingErrors = checkSpelling(rawBodyText);

    for (const { word, correction } of spellingErrors) {
      addIssue(
        urlPath,
        'spelling',
        `Possible misspelling: "${word}" (did you mean "${correction}"?)`
      );
      let wordElement: any = null;
      try {
        const loc = page.locator('body').getByText(new RegExp(`\\b${word}\\b`, 'i')).first();
        if (await loc.isVisible({ timeout: 1000 })) wordElement = loc;
      } catch { /* fall back to viewport */ }
      await captureIssueScreenshot(screenshotDir, safeName, `spelling-${word}`, page, wordElement);
    }

    // --- Broken internal links ---
    await checkBrokenInternalLinks(page, urlPath, screenshotDir, safeName);
  });
}
